### ISSUE TITLE
Project discussion

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-Deepstack#15]
**Subject:** Discussion of project I wish to write up. 
**Project:** Get alerts when someone is at my front door, similar [to this project](https://www.hackster.io/97766/announce-who-is-home-using-facial-recognition-dcc389) but with a couple of significant improvements. 

(1) Works with SIDE PROFILE. 
(2) Works with ONVIF/RTSP camera 

From discussion with @OlafenwaMoses (1) is straightforward so long as side profile images are used in training, TBD (2)

Nice to have (not a requirement )- works with Movidius/Coral USB stick

**Comment by OlafenwaMoses** [comment]
Great. Looking forward to this.

**Comment by robmarkcole** [comment]
@OlafenwaMoses can you comment on whether it is possible for Deepstack to ingest images from an ONVIF/RTSP stream?

**Comment by OlafenwaMoses** [comment]
Yes it is. If you use a camera/computer vision library to obtain the image frames from the stream, all you need is to send the obtained image frames to **DeepStack**s APIs.

Below is a link to a stackoverflow discussion showing how to read **RSTP** video stream using **OpenCV**

https://stackoverflow.com/questions/20891936/rtsp-stream-and-opencv-python

**Comment by robmarkcole** [comment]
@OlafenwaMoses yes the openCV approach works, although I hate making openCV a dependency so am also checking out ffmpeg (https://github.com/kkroening/ffmpeg-python/tree/master/examples). 

I am expanding the scope of this project to including queue processing of images, following [this](https://www.pyimagesearch.com/2018/02/05/deep-learning-production-keras-redis-flask-apache/) or this [other](https://github.com/RedisGears/EdgeRealtimeVideoAnalytics) example, any thoughts?

**Comment by OlafenwaMoses** [comment]
It will be a nice idea to have the project show DeepStack in a production environment. To ensure a better experience for the readers, I am suggesting that it can be a mini-series or 2-part collection of articles. The initial article can be a first entry project while the follow-up will be a full-fledged production setup.

For **1**, I think it will be a good idea. It can be an alert system that sends data/notifications or perform action if object(s) are detected.

For **2**, real-time object detection on a live-stream will require the GPU version, and also probably a starting mode of "Low" i.e **-e MODE=Low**, depending on the GPU specs.

**Comment by OlafenwaMoses** [comment]
Also an intruder detection system that triggers email or sound alerts when persons, vehicles or animals are detected can be a good project to write on, considering it can be very useful in warehouses, farms and restricted/monitored areas.

**Comment by robmarkcole** [comment]
Thanks for the suggestions, I think a 2 part article (or pair) is the way to go then. First article will be basic alarm monitor, with motion triggered capture of a small number of images which can be easily batch processed. Second article will be live stream, I don't have a GPU so this will require movidius/coral hardware. This second article will show how processing the live stream is both feasible on low cost hardware, and results in a more robust security system (no need to fine tune motion capture settings and no missed detections)

**Comment by OlafenwaMoses** [comment]
Alright . This is great. Thumbs up for the brilliant thinking on this. I will let you know once we have updates on the movidius/coral hardware.

**Comment by robmarkcole** [comment]
@OlafenwaMoses re article one, thinking some more it is in danger of being too similar to my earlier article https://www.hackster.io/97766/announce-who-is-home-using-facial-recognition-dcc389 I want to clearly demonstrate how we can build a system which has advantages over my previous system, e.g. easier to setup & maintain, better performance, lower cost etc. My previous article used Machinebox, so at the first instance can you comment on which features of Deepstack would make us want to choose it over the Machinebox offering for this use case?

**Comment by OlafenwaMoses** [comment]
Thanks for the comment. Let me highlights the benefits of our system compared to that of MachineBox has demonstrated in your previous article.
1) DeepStack's Face Recognition API only requires registering the faces once.
2) DeepStack only needs to be activated once.
3) DeepStack single install provides many APIs that can be used together with the Face API.
4) DeepStack runs on hardware with GPU acceleration, allowing faster and real-time Face Recognition without skipping video frames.
5) DeepStack provides endpoint security via API and Admin Keys for authentication.
6) DeepStack provides backup functionalities.

You can see all the details about these features in the Python Documentation linked below.

https://python.deepstack.cc/

**Comment by robmarkcole** [comment]
I think the other big differentiator is:

1. Deepstack has a propper object detection model (Machinebox do 'logos' using openCV I think)
2. Deepstack allows custom models 

To update you on my progress, I have setup a motion triggered camera to gather training data, this is harder to fine tune than you would think! Quite a few images are of random motion, or miss the person due to latency.

**Comment by OlafenwaMoses** [comment]
Thanks for adding those 2 facts on **DeepStack**. **DeepStack** supports detection of **80 most common objects** in offices, homes and public spaces.  The list of objects detectable are in the webpage linked below.

https://python.deepstack.cc/object-detection

I understand getting training data can be very challenging, especially in special use cases. This problem is something we are looking at critically and we are hoping to build platforms to address it in the nearest future.

**Comment by robmarkcole** [comment]
@OlafenwaMoses did you see my Discord message re mp4 endpoint? Motivation for video clips is that just taking a single image on motion I often don't catch a view of the person. Example below where we catch the back of them. Ideally I capture a 10 second clip, then use Deepstack to both identify the person and return the best frame (i.e. clear face shot)

![image](https://user-images.githubusercontent.com/11855322/59424133-52e30d00-8dcb-11e9-9bb6-fb814556dc69.png)

**Comment by OlafenwaMoses** [comment]
Yes I saw the message. I do understand the convenience and efficiency in processing the video across a time-frame on a single request. This is something we have reviewed before. We will definitely work on this and let you know once it is implemented.

**Comment by robmarkcole** [comment]
OK in the meantime I can crack on with the first article, will try get this out before I go on holiday in a couple of weeks but no promises :-)

**Comment by robmarkcole** [comment]
Moving conversation to the dedicated repo
